CastorGUI/README.md
Extention for Babylon that creates a GUI game as a layer on top of the canvas
=> CastorGUI added

DynamicTerrain/.vscode/tasks.json, DynamicTerrain/readme.md, DynamicTerrain/ts/typings/babylon.d.ts, DynamicTerrain/ts/typings/babylonx.dynamicTerrain.ts
initial port of DynamicTerrain from the JS prototype to TS
First **working** version :-)
=> DynamicTerrain first TS port

ClonerSystem/README.md, ClonerSystem/lib/babylon.d.ts, ClonerSystem/lib/babylon.marbleProceduralTexture.d.ts, ClonerSystem/src/babylonx.cloner.js, ClonerSystem/src/babylonx.cloner.ts
This is my first pullrequest and I have no idea how an extension must be structured in order to build.
In this module are 2 dependencies: 
first dependency: Babylon 4 alpha 
second dependency: dynaic texture marbleProceduralTexture
But I assume, extensions are not part of any build processes here, so the dependencies doesnt care
=> Babylon Cloner System initial 

DynamicTerrain/documentation/dynamicTerrainDocumentation.md, DynamicTerrain/documentation/dynamicTerrainExamples.md
=> cross links

canvas2D/src/Engine/babylon.shape2d.ts
http://www.html5gamedevs.com/topic/30986-canvas2d-setting-lines2d-border-thickness-not-working/#comment-177822
not working:
http://www.babylonjs-playground.com/#15C96V#28
working with fix:
http://www.babylonjs-playground.com/#15C96V#29
=> fix in Canvas2D for updating a transparent shape to opaque

LDraw/LegoConvertDat/Helpers/Text.cs, LDraw/LegoConvertDat/Program.cs, LDraw/LegoConvertDat/Services/DatLoader.cs, LDraw/LegoConvertDat/Services/LoadColors.cs
=> Fixed few bugs and hi resolution loading for dat part

recastjs/src/recastjs.cpp
All units are now cell-size based
=> Fix units for climbing

recastjs/src/recastjs.cpp, recastjs/src/recastjs.h
Fix memory corruption resulting in non accessible areas and freeze
=> navmesh memory corruption fixed

recastjs/recast.idl, recastjs/src/recastjs.cpp, recastjs/src/recastjs.h
- added an extent query to allow for finer queries on navmesh
- replace tabs with space
=> Added query extent support

CastorGUI/README.md
Update of links on the playgrond to use https
+
Add a link to the main repository.
=> Update of links on the playgrond to use https

recastjs/make.py, recastjs/recast.idl, recastjs/src/recastjs.cpp, recastjs/src/recastjs.h
Also updated the build script with the same emcc parameters as AmmoJS....waka waka
=> agent teleport and setter/getter for agent parameters

recastjs/recast.idl, recastjs/src/recastjs.cpp, recastjs/src/recastjs.h
C++ side update for https://github.com/BabylonJS/Babylon.js/pull/9139
=> Get next sub path point

recastjs/recast.idl, recastjs/src/recastjs.cpp, recastjs/src/recastjs.h
follow up https://forum.babylonjs.com/t/recast-navigation/14728/29
=> helper functions for agents

recastjs/recast.idl, recastjs/src/recastjs.cpp, recastjs/src/recastjs.h
follow up on https://forum.babylonjs.com/t/navigation-and-multiple-obstacles-lead-to-lost-references/19391
=> do not return the obstacle pointer on the stack but one in a std::list

MeshWriter/README.md
https://forum.babylonjs.com/t/text-in-3d-as-meshes/20028/6
=> Updated readme to working links.

HtmlMesh/example.js, HtmlMesh/src/html-mesh-renderer.ts, HtmlMesh/src/html-mesh.ts, HtmlMesh/src/pointer-events-capture-behavior.ts
I have made the modifications according to the opinions we discussed. Please review them again
=> repull. adding canvas overlay rendering support, optimized html scale

recastjs/CMakeLists.txt, recastjs/package.json, recastjs/recast.d.ts, recastjs/recast.idl, recastjs/src/recastjs.cpp, recastjs/src/recastjs.h
A new recast.js package will be released when this is merged
=> expose seed and computepath smooth

HtmlMesh/example.js, HtmlMesh/package-lock.json, HtmlMesh/package.json, HtmlMesh/src/html-mesh-renderer.ts, HtmlMesh/src/html-mesh.ts
This PR fixes Issue #268 (error when creation of HtmlMesh is delayed)
=> Fix for Issue #268

DynamicTerrain/documentation/dynamicTerrainDocumentation.md, DynamicTerrain/documentation/dynamicTerrainExamples.md, DynamicTerrain/readme.md
For a complete explanation of the purpose of this PR, see https://github.com/BabylonJS/Documentation/issues/1118. If the issue is to be fixed, the fix should be applied in two repos: the Documentation repo and this (Extensions) repo. I'll submit the PR for the documentation repo in a minute.
=> Change term height to depth where it refers to the Z-dimension. Also change altitude to elevation in some places.

HtmlMesh/example-rhs.js, HtmlMesh/example.js, HtmlMesh/package-lock.json, HtmlMesh/package.json, HtmlMesh/src/html-mesh-renderer.ts
HtmlMesh doesn't work with a right handed coordinate system. This pull request aims to provide support for such coordinate systems.
=> Add support for right handed coordinate systems
